import sqlite3
conn = sqlite3.connect('flight_management')

print ("Database has been created")

conn.execute("DROP TABLE IF EXISTS DESTINATIONS")
conn.execute("CREATE TABLE DESTINATIONS (SHORT_NAME VARCHAR(3) NOT NULL PRIMARY KEY, FULL_NAME VARCHAR(20))")

conn.execute("DROP TABLE IF EXISTS PILOTS")
conn.execute("CREATE TABLE PILOTS (ID INTEGER PRIMARY KEY AUTOINCREMENT, FIRST_NAME VARCHAR(20), LAST_NAME VARCHAR(20), FLIGHT_HOURS INTEGER)")

conn.execute("DROP TABLE IF EXISTS FLIGHTS")
conn.execute("CREATE TABLE FLIGHTS (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS VARCHAR(10), SCHEDULED_DEPARTURE DATETIME, EXPECTED_ARRIVAL DATETIME, PILOT_ID INTEGER, FROM_DESTINATION VARCHAR(3), TO_DESTINATION VARCHAR(3), ACTUAL_DEPARTURE DATETIME, ACTUAL_ARRIVAL DATETIME, FOREIGN KEY(PILOT_ID) REFERENCES PILOT(ID), FOREIGN KEY(FROM_DESTINATION) REFERENCES DESTINATION(SHORT_NAME), FOREIGN KEY(TO_DESTINATION) REFERENCES DESTINATION(SHORT_NAME))")

print ("Tables has been created")

conn.execute("INSERT INTO DESTINATIONS (SHORT_NAME, FULL_NAME) VALUES ('BLK', 'Blackpool International Airport')")
conn.execute("INSERT INTO DESTINATIONS (SHORT_NAME, FULL_NAME) VALUES ('LPL', 'Liverpool John Lennon Airport')")
conn.execute("INSERT INTO DESTINATIONS (SHORT_NAME, FULL_NAME) VALUES ('LBA', 'Leeds Bradford Airport')")
conn.execute("INSERT INTO DESTINATIONS (SHORT_NAME, FULL_NAME) VALUES ('EMA', 'East Midlands Airport')")
conn.execute("INSERT INTO DESTINATIONS (SHORT_NAME, FULL_NAME) VALUES ('BFS', 'Belfast International Airport')")
conn.execute("INSERT INTO DESTINATIONS (SHORT_NAME, FULL_NAME) VALUES ('GLA', 'Glasgow International Airport')")
conn.execute("INSERT INTO DESTINATIONS (SHORT_NAME, FULL_NAME) VALUES ('BRS', 'Bristol Airport')")

conn.execute("INSERT INTO PILOTS (FIRST_NAME, LAST_NAME, FLIGHT_HOURS) VALUES ('Wilbur', 'Wright', 3)")
conn.execute("INSERT INTO PILOTS (FIRST_NAME, LAST_NAME, FLIGHT_HOURS) VALUES ('Orville', 'Wright', 3)")
conn.execute("INSERT INTO PILOTS (FIRST_NAME, LAST_NAME, FLIGHT_HOURS) VALUES ('Amelia', 'Earhart', 563)")
conn.execute("INSERT INTO PILOTS (FIRST_NAME, LAST_NAME, FLIGHT_HOURS) VALUES ('Tom', 'Cruise', 2431)")

conn.commit()

print ("Database has been inialised")
