import sqlite3
conn = sqlite3.connect('flight_management')

print ("Database has been created")

conn.execute("DROP TABLE IF EXISTS DESTINATIONS")
conn.execute("CREATE TABLE DESTINATIONS (SHORT_NAME VARCHAR(3) NOT NULL PRIMARY KEY, FULL_NAME VARCHAR(20) NOT NULL)")

conn.execute("DROP TABLE IF EXISTS PILOTS")
conn.execute("CREATE TABLE PILOTS (ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, FIRST_NAME VARCHAR(20) NOT NULL, LAST_NAME VARCHAR(20) NOT NULL, FLIGHT_HOURS INTEGER DEFAULT 0)")

conn.execute("DROP TABLE IF EXISTS FLIGHTS")
conn.execute("CREATE TABLE FLIGHTS (\
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,\
STATUS VARCHAR(10) NOT NULL,\
SCHEDULED_DEPARTURE DATETIME NOT NULL,\
EXPECTED_ARRIVAL DATETIME NOT NULL,\
PILOT_ID INTEGER,\
FROM_DESTINATION VARCHAR(3) NOT NULL,\
TO_DESTINATION VARCHAR(3) NOT NULL,\
ACTUAL_DEPARTURE DATETIME,\
ACTUAL_ARRIVAL DATETIME,\
FOREIGN KEY(PILOT_ID) REFERENCES PILOT(ID),\
FOREIGN KEY(FROM_DESTINATION) REFERENCES DESTINATION(SHORT_NAME),\
FOREIGN KEY(TO_DESTINATION) REFERENCES DESTINATION(SHORT_NAME))\
")

print ("Tables has been created")

conn.execute("INSERT INTO DESTINATIONS (SHORT_NAME, FULL_NAME) VALUES ('BLK', 'Blackpool International Airport')")
conn.execute("INSERT INTO DESTINATIONS (SHORT_NAME, FULL_NAME) VALUES ('LPL', 'Liverpool John Lennon Airport')")
conn.execute("INSERT INTO DESTINATIONS (SHORT_NAME, FULL_NAME) VALUES ('LBA', 'Leeds Bradford Airport')")
conn.execute("INSERT INTO DESTINATIONS (SHORT_NAME, FULL_NAME) VALUES ('EMA', 'East Midlands Airport')")
conn.execute("INSERT INTO DESTINATIONS (SHORT_NAME, FULL_NAME) VALUES ('BFS', 'Belfast International Airport')")
conn.execute("INSERT INTO DESTINATIONS (SHORT_NAME, FULL_NAME) VALUES ('GLA', 'Glasgow International Airport')")
conn.execute("INSERT INTO DESTINATIONS (SHORT_NAME, FULL_NAME) VALUES ('BRS', 'Bristol Airport')")

conn.execute("INSERT INTO PILOTS (FIRST_NAME, LAST_NAME, FLIGHT_HOURS) VALUES ('Wilbur', 'Wright', 3)")
conn.execute("INSERT INTO PILOTS (FIRST_NAME, LAST_NAME, FLIGHT_HOURS) VALUES ('Orville', 'Wright', 3)")
conn.execute("INSERT INTO PILOTS (FIRST_NAME, LAST_NAME, FLIGHT_HOURS) VALUES ('Amelia', 'Earhart', 563)")
conn.execute("INSERT INTO PILOTS (FIRST_NAME, LAST_NAME, FLIGHT_HOURS) VALUES ('Tom', 'Cruise', 2431)")

conn.execute("INSERT INTO FLIGHTS(STATUS, SCHEDULED_DEPARTURE, EXPECTED_ARRIVAL, PILOT_ID, FROM_DESTINATION, TO_DESTINATION, ACTUAL_DEPARTURE, ACTUAL_ARRIVAL)\
             VALUES('Arrived', DATETIME('NOW', '-25 hours'), DATETIME('NOW', '-24 hours'), 4, 'BLK', 'BRS', DATETIME('NOW', '-25 hours'), DATETIME('NOW', '-24 hours'))")

conn.execute("INSERT INTO FLIGHTS(STATUS, SCHEDULED_DEPARTURE, EXPECTED_ARRIVAL, PILOT_ID, FROM_DESTINATION, TO_DESTINATION, ACTUAL_DEPARTURE, ACTUAL_ARRIVAL)\
             VALUES('Departed', DATETIME('NOW', '-2 hours'), DATETIME('NOW', '+1 hours'), 3, 'BRS', 'GLA', DATETIME('NOW', '-2 hours'), NULL)")

conn.execute("INSERT INTO FLIGHTS(STATUS, SCHEDULED_DEPARTURE, EXPECTED_ARRIVAL, PILOT_ID, FROM_DESTINATION, TO_DESTINATION, ACTUAL_DEPARTURE, ACTUAL_ARRIVAL)\
             VALUES('Scheduled', DATETIME('NOW', '-1 hours'), DATETIME('NOW', '+2 hours'), 2, 'BFS', 'EMA', NULL, NULL)")

conn.commit()

print ("Database has been inialised")
